version: '3.8'

services:
  api:
    container_name: nestjs-typeorm
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - PORT=5000
      - NODE_ENV=production
      - ENABLE_CORS=true
      - ACCESS_TOKEN_SECRET=hahaha
      - ACCESS_TOKEN_EXPIRES_IN=7d
      - BCRYPT_ROUNDS=12
      - TYPEORM_URL=postgresql://postgres:123@host.docker.internal:5432/postgres?schema=demo
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_SCHEMA=demo
      - TYPEORM_SEEDS=/src/database/seeds/*.{.ts,.js}
      - TYPEORM_FACTORIES=/src/database/factories/*.{.ts,.js}
      - TYPEORM_LOGGING=true
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_SSL=false
      - TYPEORM_MAX_CONNECTIONS=100
      - MAIL_FROM=info@nestjs.com
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USER=fba000ad0f4767
      - MAIL_PASSWORD=4f5d49826af6ae
      - MAIL_SECURE=false
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=Admin@123
      - SWAGGER_USER=admin
      - SWAGGER_PASSWORD=Admin@123
    ports:
      - '5000:5000'
