version: '3.8'

services:
  api:
    container_name: nestjs-typeorm
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - '5000:5000'
